# Generated by Django 2.1.7 on 2019-02-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Картинка')),
                ('urlImg', models.URLField(blank=True, null=True, verbose_name='Ссылка на картинку')),
            ],
        ),
    ]
